### PR TITLE
Update kinematics.py

### PR DESCRIPTION
**Pull request by MrLeeYH**
question

### CODE REVIEW

**Review by jjcheung — COMMENTED** [review]
No need.

**Comment by jjcheung** [comment]
No need.

**Comment by EugeneQuek** [comment]
Test!

**Comment by MrLeeYH** [comment]
finished test, no email yet, in 5 seconds

**Comment by MrLeeYH** [comment]
image
oh wait, have

**Comment by ngmeichan** [comment]
What will happen?

**Comment by jjcheung** [comment]
hello :)

**Pull request closed without merging**
